"""Create metadata table to store host-stale notification successful runs

Revision ID: 4f0b36e6cf28
Revises: 1e276ea9970d
Create Date: 2025-01-24 15:30:37.555780

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f0b36e6cf28"
down_revision = "1e276ea9970d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hbi_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="hbi",
    )
    op.create_unique_constraint("hbi_metadata_unique_constraint", "hbi_metadata", ["name", "type"], schema="hbi")


def downgrade():
    op.drop_constraint("hbi_metadata_unique_constraint", "hbi_metadata", schema="hbi")
    op.drop_table("hbi_metadata", schema="hbi")

    # ### end Alembic commands ###
